# -*- coding: utf-8 -*-
"""ProblemSet2_Solution.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12LTgYod0TUuyQkHQXYT1WudNCsnzXwha
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.stats import chisquare, chi2
from numpy import linalg # <-- ADDED THIS
import time

# --- Constants from the problem set ---
N_EVENTS = 10000       # Number of events per experiment
N_PVAL_LOOPS = 1000    # Number of experiments for p-value (Task 1)
N_FIT_LOOPS = 500      # Number of experiments for fitting (Task 4/5)
N_BINS = 50            # Number of bins for chi-square
X_MIN = -1.0           # x-domain min
X_MAX = 1.0            # x-domain max

# --- PDF and CDF Definitions ---

def f0(x):
    """
    The "true" PDF (nature), f_0(x).
    """
    return (3/8) * (1 + x**2)

def F0(x):
    """
    The analytical integral (antiderivative) of f0(x),
    used for calculating expected counts.
    """
    return (3/8) * (x + (x**3 / 3))

def f_fit(x, A):
    """
    The model PDF we are fitting, f(x; A).
    """
    return (3/8) * (1 + x**2 + A * x)

def F_fit(x, A):
    """
    The analytical integral (antiderivative) of f_fit(x, A),
    used for calculating expected counts from the fit.
    """
    return (3/8) * (x + (x**3 / 3) + A * (x**2 / 2))

# --- Event Generator ---

def generate_f0(N):
    """
    Generate N events according to f0(x) using the
    Acceptance-Rejection (Hit-or-Miss) method.
    """
    # Max value of f0(x) on [-1, 1] is at x = +/- 1
    f_max = f0(X_MAX) # f_max = 3/4

    accepted_events = []
    while len(accepted_events) < N:
        # Generate N_try events. Efficiency is ~2/3, so we add a buffer.
        N_try = int((N - len(accepted_events)) / 0.66) + 1

        # 1. Generate trial x values uniformly in the domain
        x_trial = np.random.uniform(X_MIN, X_MAX, N_try)

        # 2. Generate trial y values uniformly in [0, f_max]
        y_trial = np.random.uniform(0, f_max, N_try)

        # 3. Calculate the PDF value at the trial x
        pdf_val = f0(x_trial)

        # 4. Accept events where y_trial <= PDF(x_trial)
        accepted = x_trial[y_trial <= pdf_val]
        accepted_events.extend(accepted)

    # Return exactly N events
    return np.array(accepted_events[:N])

# --- Helper Functions ---

def get_expected_counts(N_total, bins, CDF_func, *args):
    """
    Calculates the expected counts in each bin for a given CDF.
    """
    # Calculate CDF at bin edges
    cdf_edges = CDF_func(bins, *args)
    # Expected probability in each bin is the difference in CDF
    bin_probabilities = np.diff(cdf_edges)
    # Expected counts
    return N_total * bin_probabilities

def plot_histogram(data, title, xlabel, bins=50):
    """Utility function to plot a histogram."""
    plt.figure(figsize=(10, 6))
    plt.hist(data, bins=bins, density=True, edgecolor='black', alpha=0.7)
    plt.title(title)
    plt.xlabel(xlabel)
    plt.ylabel('Density')
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.show()

# --- Main Task Functions ---

def task_1_pvalue_distribution_f0():
    """
    Solves tasks from:
    1. Repeat 1000 times:
       - Generate 10000 events from f0(x)
       - Calculate p-value with respect to f0(x)
    2. Show the distribution of the p-values.
    """
    print("--- Starting Task 1 (p-value dist. w.r.t. f0) ---")
    p_values = []
    bin_edges = np.linspace(X_MIN, X_MAX, N_BINS + 1)

    # Calculate expected counts (E_i) for f0(x)
    # This is constant for all experiments
    expected_counts_f0 = get_expected_counts(N_EVENTS, bin_edges, F0)

    # Filter out bins with zero expected counts to avoid errors in chisquare
    # (though for this PDF, all bins should be > 0)
    non_zero_mask = expected_counts_f0 > 0
    if not np.all(non_zero_mask):
        print("Warning: Some bins have zero expected counts. Adjusting...")


    for i in range(N_PVAL_LOOPS):
        # Generate data according to f0(x)
        data = generate_f0(N_EVENTS)

        # Get observed counts (O_i)
        observed_counts, _ = np.histogram(data, bins=bin_edges)

        # Calculate p-value
        # ddof=0: degrees of freedom = k - 1 (k=num_bins)
        # We only use the bins where expected counts are non-zero
        stat, p_val = chisquare(
            f_obs=observed_counts[non_zero_mask],
            f_exp=expected_counts_f0[non_zero_mask],
            ddof=0
        )
        p_values.append(p_val)

    print(f"Generated {len(p_values)} p-values.")

    # Plot the p-value distribution
    plot_histogram(p_values,
                   f'p-value Distribution (vs. $f_0(x)$) over {N_PVAL_LOOPS} Experiments',
                   'p-value',
                   bins=20)
    print("Discussion: The p-value distribution should be uniform from 0 to 1,")
    print("as we are testing the data against the true hypothesis.\n")

def task_2_theory():
    """
    Calculates and prints the theoretical MVB.
    """
    print("--- Starting Task 2 (Theory: MVB & Analytical) ---")

    # Analytical calculation of the Minimum Variance Bound (MVB)
    # Var(A_hat) >= 1 / I(A) where I is Fisher Information
    # I(A) = N * I_single(A)
    # I_single(0) = (3/4) * (1 - pi/4)
    I_single_0 = (3/4) * (1 - np.pi/4)
    I_N_0 = N_EVENTS * I_single_0

    # Your PDF had a different calculation, let's check:
    # I(0) = 3/8 * integral(x^2 / (1+x^2)) dx from -1 to 1
    # integral(1 - 1/(1+x^2)) = [x - atan(x)] from -1 to 1
    # = (1 - pi/4) - (-1 - (-pi/4)) = (1 - pi/4) - (-1 + pi/4) = 2 - pi/2
    # I(0) = 3/8 * (2 - pi/2) = 3/4 * (1 - pi/4)
    # Yes, the calculation is correct.

    mvb_variance = 1.0 / I_N_0
    mvb_std_dev = np.sqrt(mvb_variance)

    print(f"MVB (Min. Variance Bound) for A at N={N_EVENTS} (true A=0):")
    print(f"  I_single(0) = {I_single_0:.5f}")
    print(f"  I_N(0) = {I_N_0:.2f}")
    print(f"  Var(A_hat) >= 1 / I_N(0) = {mvb_variance:.4e}")
    print(f"  sigma(A_hat) >= {mvb_std_dev:.5f}")

    print("\nFor the analytical expression of A_hat (small A):")
    print("  A_hat approx [sum(x_i / (1+x_i^2))] / [sum(x_i^2 / (1+x_i^2)^2)]")
    print("  We will use numerical Maximum Likelihood, as requested.\n")
    return mvb_std_dev

def task_3_single_fit_and_graphical_error():
    """
    Solves task from:
    - Generate 10000 events from f0(x)
    - Fit with f(x;A) using numerical/graphical likelihood method
    - Determine A and its error ΔA
    """
    print("--- Starting Task 3 (Single Fit & Graphical Error) ---")

    # 1. Define the Negative Log-Likelihood (NLL) function
    def nll(A_param, data):
        A = A_param[0] # Minimizer passes A as an array

        # Calculate PDF values for all data points
        pdf_vals = f_fit(data, A)

        # IMPORTANT: Check for invalid PDF values (<= 0)
        # This can happen if the minimizer tries a bad 'A'
        if np.any(pdf_vals <= 0):
            return np.inf # Return "infinite" cost

        # Return the NLL
        return -np.sum(np.log(pdf_vals))

    # 2. Generate the data
    data = generate_f0(N_EVENTS)

    # 3. Minimize the NLL
    print("Finding ML estimate for A...")
    # Initial guess for A is 0.0
    # We use 'BFGS' method which gives an inverse Hessian for error calculation
    result = minimize(nll, x0=[0.0], args=(data,), method='BFGS')

    A_hat = result.x[0]
    nll_min = result.fun

    # 4. Get error from the Hessian (standard ML method)
    # Var(A) = (Hessian^-1)_ii
    A_err = 0.0
    try:
        # Inverse Hessian (covariance matrix)
        A_err = np.sqrt(result.hess_inv[0, 0])
        print(f"  Fit Result: A = {A_hat:.5f} ± {A_err:.5f}")
    except (AttributeError, IndexError, linalg.LinAlgError): # <-- FIXED THIS
        print(f"  Fit Result (no Hessian): A = {A_hat:.5f} (could not get error)")
        # Fallback for error scanning
        A_err = 0.03 # Use a guess near the MVB

    # 5. Show the "graphical method"
    # We plot NLL(A) vs. A and show the NLL_min + 0.5 intercept
    print("Plotting NLL curve for graphical error...")

    # Create a range of A values around the minimum
    scan_range = A_err if A_err > 0 else 0.03
    A_scan = np.linspace(A_hat - 3*scan_range, A_hat + 3*scan_range, 200)
    nll_scan = [nll([A], data) for A in A_scan]

    plt.figure(figsize=(10, 6))
    plt.plot(A_scan, nll_scan, label='-ln(L(A))')

    # Plot the minimum
    plt.axvline(A_hat, color='r', linestyle='--', label=f'A_hat = {A_hat:.4f}')
    plt.axhline(nll_min, color='gray', linestyle=':', label='NLL_min')

    # Plot the 1-sigma (ΔA) error line
    plt.axhline(nll_min + 0.5, color='b', linestyle=':', label='NLL_min + 0.5 (1σ)')

    # Show the intercept points
    if A_err > 0:
        plt.axvline(A_hat - A_err, color='b', linestyle=':', alpha=0.7)
        plt.axvline(A_hat + A_err, color='b', linestyle=':', alpha=0.7)

    plt.title("Graphical Method for Likelihood Error")
    plt.xlabel("Parameter A")
    plt.ylabel("Negative Log-Likelihood (NLL)")
    plt.ylim(nll_min - 1, nll_min + 5) # Zoom in around the minimum
    plt.legend()
    plt.grid(True, linestyle='--', alpha=0.6)
    plt.show()

def task_4_5_fit_loop_and_pvalue_dist():
    """
    Solves tasks from:
    - Repeat 500 times:
      - Generate N=10000 from f0(x)
      - Fit with f(x;A) to get A_hat and DeltaA_hat
      - Calculate p-value of data w.r.t. f(x; A_hat)
    """
    print("\n--- Starting Task 4 & 5 (500 Fit Loops) ---")
    print("This will take a few minutes...")

    # NLL function (nested for performance, accesses 'data' from loop)
    def nll_loop(A_param, data):
        pdf_vals = f_fit(data, A_param[0])
        if np.any(pdf_vals <= 0):
            return np.inf
        return -np.sum(np.log(pdf_vals))

    A_hat_list = []
    A_err_list = []
    p_values_fit_list = []
    bin_edges = np.linspace(X_MIN, X_MAX, N_BINS + 1)

    start_time = time.time()

    for i in range(N_FIT_LOOPS):
        # 1. Generate data
        data = generate_f0(N_EVENTS)

        # 2. Fit data
        result = minimize(nll_loop, x0=[0.0], args=(data,), method='BFGS')

        A_hat = result.x[0]

        # 3. Get error from Hessian
        try:
            A_err = np.sqrt(result.hess_inv[0, 0])
            A_hat_list.append(A_hat)
            A_err_list.append(A_err)
        except Exception as e:
            # Skip if fit failed or Hessian was bad
            continue

        # --- Task 5: p-value w.r.t. f(x; A_hat) ---

        # 4. Get observed counts
        observed_counts, _ = np.histogram(data, bins=bin_edges)

        # 5. Get expected counts *from the fitted model*
        expected_counts_fit = get_expected_counts(N_EVENTS, bin_edges, F_fit, A_hat)

        # 6. Calculate p-value
        # We must account for the fitted parameter
        # ddof = 1 (degrees of freedom = k - 1 - ddof)
        # So ndf = N_BINS - 1 - 1 = N_BINS - 2

        # Filter bins where expected counts are <= 0 (can happen with bad fits)
        non_zero_mask = expected_counts_fit > 0

        # We need at least (k - 1 - ddof) > 0 degrees of freedom
        if np.sum(non_zero_mask) > 1:
            stat, p_val = chisquare(
                f_obs=observed_counts[non_zero_mask],
                f_exp=expected_counts_fit[non_zero_mask],
                ddof=1
            )
            p_values_fit_list.append(p_val)

        if (i + 1) % 50 == 0:
            print(f"  ... completed {i+1}/{N_FIT_LOOPS} loops.")

    end_time = time.time()
    print(f"Fit loops finished in {end_time - start_time:.2f} seconds.")

    # --- Task 4 Results ---
    print("\n--- Results for Task 4 ---")

    # Plot A_hat distribution
    # CHANGED from f-string to %-formatting to avoid strange errors
    plot_histogram(A_hat_list,
                   'Distribution of $\hat{A}$ (%d experiments)' % len(A_hat_list),
                   '$\hat{A}$')

    # Plot DeltaA_hat distribution
    # CHANGED from f-string to %-formatting to avoid strange errors
    plot_histogram(A_err_list,
                   'Distribution of $\Delta\hat{A}$ (%d experiments)' % len(A_err_list),
                   '$\Delta\hat{A}$ (Reported Error)')

    # Discussion
    A_hat_mean = np.mean(A_hat_list)
    A_hat_std = np.std(A_hat_list)
    A_err_mean = np.mean(A_err_list)

    print("Discussion of Task 4 results:")
    print(f"  Mean of fitted A_hat:      {A_hat_mean:.5f} (expected ~0)")
    print(f"  Std. Dev. of A_hat dist: {A_hat_std:.5f} (the 'true' error)")
    print(f"  Mean of reported Delta_A:  {A_err_mean:.5f} (the 'estimated' error)")

    # Compare to MVB
    mvb_sigma = np.sqrt(1.0 / (N_EVENTS * (3/4) * (1 - np.pi/4)))
    print(f"  Theoretical MVB sigma:     {mvb_sigma:.5f}")

    print("\n  We expect: (Mean of A_hat) approx 0, since the true value is 0.")
    print("  We expect: (Std. Dev. of A_hat) approx (Mean of Delta_A) approx (MVB sigma).")
    print("  This confirms our fit and error estimation are working correctly.")

    # --- Task 5 Results ---
    print("\n--- Results for Task 5 ---")

    # Plot p-value distribution
    # CHANGED from f-string to %-formatting to avoid strange errors
    plot_histogram(p_values_fit_list,
                   'p-value Dist. (vs. $f(x; \hat{A})$) over %d Experiments' % len(p_values_fit_list),
                   'p-value',
                   bins=20)

    print("Discussion: This p-value distribution should also be uniform.")
    print("This shows that our fitted model, f(x; A_hat), is a good")
    print("description of the data (which it should be, as the true")
    print("model f0 is a subset of the f(x;A) family).\n")

# --- Main execution ---

if __name__ == "__main__":

    # Run Task 1
    task_1_pvalue_distribution_f0()

    # Run Task 2
    task_2_theory()

    # Run Task 3
    task_3_single_fit_and_graphical_error()

    # Run Task 4 & 5
    task_4_5_fit_loop_and_pvalue_dist()

    print("--- All tasks complete. ---")