# -*- coding: utf-8 -*-
"""Set3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x2HLCKif8Ojkz3OetSuOBwnnKEyz1j0U
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import chi2, norm, expon

# [cite_start]--- Configuration & Parameters [cite: 7-11, 638-644] ---
np.random.seed(42)  # For reproducible results

# Physics Parameters
m_min, m_max = 100.0, 140.0
n_bins = 40
bin_edges = np.linspace(m_min, m_max, n_bins + 1)
bin_width = (m_max - m_min) / n_bins

# Background Parameters (Exponential)
alpha = 0.0218
B_rate_per_year = 80000

# Signal Parameters (Gaussian)
m_H = 126.5
sigma_H = 2.0
S_rate_per_year = 400

# 5 sigma threshold
p_5sigma = 2.9e-7

# --- 1. Define Expected Counts per Bin ---
# We compute probabilities by integrating the PDFs over the bin widths
# (More precise than midpoint rule)

def get_expected_counts(years=1.0):
    # Background: proportional to e^(-alpha * m)
    # Integral of e^(-ax) is (-1/a)e^(-ax)
    # Norm constant C ensures integral over [100, 140] is 1

    # Unnormalized bin integrals
    b_integrals = (np.exp(-alpha * bin_edges[:-1]) - np.exp(-alpha * bin_edges[1:])) / alpha
    b_total_integral = (np.exp(-alpha * m_min) - np.exp(-alpha * m_max)) / alpha
    b_probs = b_integrals / b_total_integral

    # Signal: Gaussian CDF differences
    s_probs = norm.cdf(bin_edges[1:], loc=m_H, scale=sigma_H) - \
              norm.cdf(bin_edges[:-1], loc=m_H, scale=sigma_H)
    # Renormalize signal to be strictly inside window (truncation effect is negligible here but good practice)
    s_probs /= (norm.cdf(m_max, loc=m_H, scale=sigma_H) - norm.cdf(m_min, loc=m_H, scale=sigma_H))

    # Scale by rate and time
    B_expected = B_rate_per_year * years * b_probs
    S_expected = S_rate_per_year * years * s_probs

    return B_expected, S_expected

# --- 2. Simulation Function ---

def run_toys(years, n_toys):
    B_exp, S_exp = get_expected_counts(years)
    Total_exp = B_exp + S_exp # True model is S+B

    # Generate observed data (Poisson fluctuations around S+B)
    # Shape: (n_toys, n_bins)
    obs_counts = np.random.poisson(Total_exp, size=(n_toys, n_bins))

    # Compute Chi-Squared against Null Hypothesis (Background Only)
    # Chi2 = sum( (Obs - Exp_B)^2 / Exp_B )
    chi2_vals = np.sum((obs_counts - B_exp)**2 / B_exp, axis=1)

    # Compute p-values (Survival function of Chi2 with 40 dof)
    p_vals = chi2.sf(chi2_vals, df=n_bins)

    return p_vals

# --- 3. Generate Data and Plots ---

# [cite_start]PLOT 1: Year 1 P-value Distribution [cite: 753, 951]
print("Simulating Year 1...")
p_vals_yr1 = run_toys(years=1.0, n_toys=100000)

plt.figure(figsize=(7, 5))
plt.hist(p_vals_yr1, bins=50, range=(0, 1), density=False, color='#5DADE2', edgecolor='white', alpha=0.8)
plt.xlabel("p-value ($H_0$)", fontsize=12)
plt.ylabel("Number of Experiments", fontsize=12)
plt.title(f"Distribution of p-values (1 Year, $S+B$ Data)\nMean p-value = {np.mean(p_vals_yr1):.4f}", fontsize=14)
plt.grid(axis='y', alpha=0.3)
plt.axvline(np.mean(p_vals_yr1), color='red', linestyle='--', label=f'Mean: {np.mean(p_vals_yr1):.3f}')
plt.legend()
plt.tight_layout()
plt.savefig('pvalue_dist_1yr.png', dpi=300)
print("Saved pvalue_dist_1yr.png")


# [cite_start]SCANS for Years 1-10 [cite: 811, 955-956]
years_scan = np.arange(1, 11)
mean_p_vals = []
prob_5sigma = []

print("Scanning Years 1-10...")
for y in years_scan:
    # Use fewer toys for scan to be quick, or 100k for precision.
    # 20k is usually enough for mean, but need more for rare 5-sigma events at low years.
    # We use 50k here for a good balance.
    p = run_toys(years=y, n_toys=50000)

    # Question 2 metric: Expected Significance (Mean p-value)
    mean_p_vals.append(np.mean(p))

    # Question 3 metric: Probability of 5 sigma discovery
    # Count how many p-values are <= 2.9e-7
    count_sig = np.sum(p <= p_5sigma)
    prob_5sigma.append(count_sig / len(p))
    print(f"Year {y}: Mean p={mean_p_vals[-1]:.2e}, Prob 5sig={prob_5sigma[-1]:.3f}")

# PLOT 2: Expected p-value vs Time (Question 2)
plt.figure(figsize=(7, 5))
plt.plot(years_scan, mean_p_vals, 'o-', linewidth=2, color='#2874A6', label=r'$\mathbb{E}[p(T)]$')
plt.axhline(p_5sigma, color='red', linestyle='--', label=r'$5\sigma$ Threshold ($2.9 \times 10^{-7}$)')
plt.yscale('log')
plt.xlabel("Running Time (Years)", fontsize=12)
plt.ylabel("Expected p-value", fontsize=12)
plt.title("Expected Significance vs. Time", fontsize=14)
plt.grid(True, which="both", alpha=0.3)
plt.legend()
plt.xticks(years_scan)
plt.tight_layout()
plt.savefig('significance_vs_time.png', dpi=300)
print("Saved significance_vs_time.png")


# PLOT 3: Probability of 5 sigma vs Time (Question 3)
plt.figure(figsize=(7, 5))
plt.plot(years_scan, prob_5sigma, 'o-', linewidth=2, color='#229954', label=r'$P(p \leq 5\sigma)$')
plt.axhline(0.95, color='red', linestyle='--', label='95% Probability Target')
plt.xlabel("Running Time (Years)", fontsize=12)
plt.ylabel("Probability of $5\sigma$ Discovery", fontsize=12)
plt.title("Probability of Claiming Discovery vs. Time", fontsize=14)
plt.grid(True, alpha=0.3)
plt.yticks(np.arange(0, 1.1, 0.1))
plt.xticks(years_scan)
plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig('probability_vs_time.png', dpi=300)
print("Saved probability_vs_time.png")